
export const REGISTER_USER = 'LOGIN_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const SET_USER = 'SET_USER'
export const SET_USER_ERROR = 'SET_USER_ERROR'

export const LOAD_PROJECTS = 'LOAD_PROJECTS'
export const SET_PROJECTS = 'SET_PROJECTS'

export const LOAD_PAGES = 'LOAD_PAGES'
export const SET_PAGES = 'SET_PAGES'

export const SET_STATUS = "SET_STATUS";

export const ADD_ITEM = "ADD_ITEM"; 

export const CHANGE_SELECTED_ITEM = "CHANGE_SELECTED_ITEM";

export const SET_DYNAMIC_ITEM = "SET_DYNAMIC_ITEM"; 
export const REMOVE_DYNAMIC_ITEM = "REMOVE_DYNAMIC_ITEM"; 

export const SELECT_ITEM = "SELECT_ITEM";
export const UNSELECT_ITEMS = "UNSELECT_ITEMS";

export const HIGHLIGHT_ITEM = "HIGHLIGHT_ITEM";

export const GROUP_SELECTED_ITEMS = "GROUP_SELECTED_ITEMS"
// export const UNGROUP_SELECTED_ITEMS = "UNGROUP_SELECTED_ITEMS"

export const START_INTERACTION = "START_INTERACTION";

export const MOUSE_MOVE = "MOUSE_MOVE";
export const MOUSE_DOWN = "MOUSE_DOWN";
export const MOUSE_UP = "MOUSE_UP";