language: node_js
node_js:
  - "8"

before_script:
  - npm install -g firebase-tools

script:
  - echo "build the application"
  - yarn test
  - yarn build


deploy:
  - firebase deploy --token $FIREBASE_TOKEN
