language: node_js
node_js:
  - "8"

script:
  - echo "build the application"
  - yarn test
  - yarn build

after_success:
  - echo "deploy the application"
  - npm run firebase -- deploy --token $FIREBASE_TOKEN
