language: node_js
node_js:
  - "8"

install:
  - echo "install front-end"
  - yarn install
  - echo "install back-end"
  - cd server
  - yarn install
  - cd ..

before_script:
  - npm install -g firebase-tools

script:
  - echo "build the front-end"
  - yarn test
  - yarn build
  - echo "build the back-end"
  - cd server
  - yarn test
  - cd ..

before_deploy:
  cd server

after_deploy:
  cd ..

deploy:
    provider: azure_web_apps
    verbose: true

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

