language: node_js
node_js:
  - "8"

install:
  - npm install -g firebase-tools

script:
  - echo "build the application"
  - yarn test
  - yarn build


deploy:
  provider: azure_web_apps
  on:
    condition: $TRAVIS_BRANCH != "master"
