language: node_js
node_js:
  - "8"

install:
  - yarn install
  - cd server
  - yarn install

before_script:
  - npm install -g firebase-tools

script:
  - echo "build the front-end"
  - yarn test
  - yarn build
  - echo "build the back-end"
  - cd server
  - yarn test

before_deploy:
  cd server

deploy:
    provider: azure_web_apps
    verbose: true

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

before_deploy:
  cd server

