language: node_js
node_js:
  - "8.11.4"

install:
  - echo "install back-end"
  - yarn install
  - echo "install front-end"
  - cd client
  - yarn install
  - cd ..

script:
  - echo "build the back-end"
  - echo "skip yarn test"
  - echo "build the front-end"
  - cd client
  - scripts/prebuild.sh
  - yarn test
  - yarn build
  - cd ..

deploy:
    provider: azure_web_apps
    verbose: true

after_success:
  - npm install -g firebase-tools
  - cd client
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
    slack: team-cs2:U88OxB1DxzsOl0P1VHz20wwU
    