

export const IA_GENERATE_RECTANGLE = "IA_GENERATE_RECTANGLE";
export const IA_GENERATE_LINE = "IA_GENERATE_LINE";
export const IA_GENERATE_CIRCLE = "IA_GENERATE_CIRCLE";
export const IA_SELECT_ITEM = "IA_SELECT_ITEM";
export const IA_CONNECT_ITEMS = "IA_CONNECT_ITEMS";
